version: '3.1'

services:
    database_dev:
        container_name: series_movies_dev_db
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dev_password
            - POSTGRES_DB=series_movies_dev_db
        ports:
            - "5433:5432"
            - "5434:5432"
        volumes:
            - ./ops/database:/docker-entrypoint-initdb.d

    database_test:
        container_name: series_movies_test_db
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=test_password
            - POSTGRES_DB=series_movies_test_db
        ports:
            - "5435:5432"
            - "5436:5432"
        volumes:
            - ./ops/database:/docker-entrypoint-initdb.d